version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    commit-message:
      prefix: "ci"
  - package-ecosystem: npm
    directory: /web
    schedule:
      interval: monthly
    commit-message:
      prefix: "chore(web)"
    groups:
      web-dependencies:
        patterns: ["*"]
  - package-ecosystem: swift
    directory: /app
    schedule:
      interval: monthly
    commit-message:
      prefix: "chore(app)"
